DROP DATABASE DB_VECINDAD;
CREATE DATABASE DB_VECINDAD;
USE DB_VECINDAD;

CREATE TABLE USERS (
  user_id INT NOT NULL AUTO_INCREMENT ,
  user_name VARCHAR(255) NOT NULL ,
  user_first_surname VARCHAR(255) NOT NULL ,
  user_second_surname VARCHAR(255) NOT NULL ,
  user_phone VARCHAR(255) NOT NULL ,
  user_email VARCHAR(255) NOT NULL ,
  user_address VARCHAR(255) NOT NULL,
  user_password VARCHAR(255) NOT NULL ,
  user_city VARCHAR(255) NOT NULL ,
  user_date DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id) 
  )
ENGINE = InnoDB;

CREATE TABLE CATEGORIES (
  category_id INT NOT NULL AUTO_INCREMENT  ,
  category_name VARCHAR(100) NOT NULL ,
  category_date DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX category_id_UNIQUE (category_id ASC),
  PRIMARY KEY (category_id)
  )
ENGINE = InnoDB;

CREATE TABLE NOTICES (
  notice_id INT NOT NULL AUTO_INCREMENT,
  notice_body TEXT NOT NULL,
  notice_status TEXT NOT NULL,
  notice_date DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  category_id INT NOT NULL,
  PRIMARY KEY (notice_id)
)
ENGINE = InnoDB;